### ISSUE TITLE
Confirmation de validation du formulaire

### ISSUE THREAD

**Issue by ArnauddeChampsavin** [consultation-gouv/consultation.gouv.fr#21]
En tant qu'utilisateur,
Je veux voir s'afficher 
"Formulaire validé ! 
Un lien d'accès à votre consultation vous a été envoyé par mail." lorsque mon formulaire de génération de consultation est rempli correctement et que je clique sur "Lancez votre consultation !".
Afin de savoir que ma consultation a bien été générée

![formulaire valide](https://user-images.githubusercontent.com/39947713/41843577-270fc178-786e-11e8-8fe2-ccddb9a857bc.jpg)

**Comment by consultationgouv** [comment]
Note : ce bug est en fait lié à la plateforme, et non au site statique.

**Comment by consultationgouv** [comment]
C'est fait, et dispo en pprod. Par exemple via https://deploiement.pprod.consultation.etalab.gouv.fr/outil/cap-collectif
