### ISSUE TITLE
Mettre arnaud.etalab@data.gouv.fr en adresse contact

### ISSUE THREAD

**Issue by ArnauddeChampsavin** [consultation-gouv/consultation.gouv.fr#24]
Créer l'adresse arnaud.etalab@data.gouv.fr
Remplacer contact@data.gouv.fr par arnaud.etalab@data.gouv.fr

**Comment by sdelafond** [comment]
Comme vu avec Arnaud, on s'assurera plutôt que contact@ contient bien tous les destinataires souhaités.
