### ISSUE TITLE
Export des informations transmises par les nouveaux formulaires remplis

### ISSUE THREAD

**Issue by adechampsavin** [consultation-gouv/consultation.gouv.fr#49]
Avoir un export quotidien avec toutes les nouvelles informations (nom, nom de la consultation, adresse mail etc...) fournies par les formulaires de demande de génération de consultation.

**Comment by consultationgouv** [comment]
1/2d

**Comment by consultationgouv** [comment]
L'export est en place : un email est envoyé chaque jour, avec les consultations ouvertes la veille. S'il n'y a eu aucune consultation, aucun email n'est envoyé.
