### ISSUE TITLE
Tracking Piwik sur deploiement.consultation.gouv.fr

### ISSUE THREAD

**Issue by ArnauddeChampsavin** [consultation-gouv/consultation.gouv.fr#56]
Rajouter le tracking Piwik notamment sur : 
- https://deploiement.consultation.etalab.gouv.fr/outil/cap-collectif
- https://deploiement.consultation.etalab.gouv.fr/outil/assembl
- https://deploiement.consultation.etalab.gouv.fr/outil/democracyos
- https://consultation.etalab.gouv.fr/outil/nova-ideo.html

**Comment by consultationgouv** [comment]
Didn't mean to close this with the initial PR.

**Comment by consultationgouv** [comment]
Done; visits to the deployment pages are now logged by piwik.
