### ISSUE TITLE
Tabbed links on "best practices" page do not work

### ISSUE THREAD

**Issue by patcon** [consultation-gouv/consultation.gouv.fr#6]
## Platforms

Ubuntu 10.04
FF 49.0.2
Chrome Version 59.0.3071.115 (Official Build) (64-bit)

## Steps to Reproduce

1. Go to the [best practices page](https://consultation.etalab.gouv.fr/laconsultation.html)
2. See that "Avant la consultation" page loads fine.
3. Click "Pendant la consultation" or "Apres la consultation" tab.

## Observed

Clicking links has no effect.

## Expected

Clicking on the links would load the pages.

## Local testing

I spun up a local version of the site and confirmed that the public codebase works fine locally. It  seems that much of the text is different, so I'm unsure if the public code is up-to-date. On the local site, clicking the tabs works fine.

Digging a little deeper showed that on the live site, this patch seems to have been applied, adding a `type="null"` bit to the script tag.

```patch
diff --git a/laconsultation.html b/laconsultation.html
index d6127af..920d0a0 100644
--- a/laconsultation.html
+++ b/laconsultation.html
@@ -207,6 +207,6 @@ additional_css: laconsultation
 
 </section>
 
-<script>
+<script type="null">
   $('#bonnes-pratiques .menu .item').tab();
 </script>
\ No newline at end of file
```

Adding this on the local site caused it to fail similarly.

Anyhow, not sure how that might have ended up on the production site, but hopefully it's simple to fix :)

**Comment by consultationgouv** [comment]
Working now.

**Comment by sdelafond** [comment]
FTR, Forestry.io happily adds type="null" to scripts tags when a page is edited in the WYSIWYG HTML editor. Thankfully it's going away soon.
